services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/redis
    networks:
      - app
    restart: unless-stopped
  postgres:
    image: postgres:16.4-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/postrges
    networks:
      - app
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6610/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - 6610:6610
    networks:
      - app
  nginx:
    image: nginx:stable-alpine3.20-perl
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local